server:
  port: 7070
spring:
  liquibase:
    change-log: db/db.changelog-main.yml
#logging:
#  level:
#    root: debug
  servlet:
    multipart:
      max-file-size: 50MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
