server:
  port: 7070
spring:
  liquibase:
    change-log: db/db.changelog-main.yml
  servlet:
    multipart:
      max-file-size: 50MB
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    root: error
sentry:
  dsn: https://e10e37c6e1d9066b8c93bafefc540df5@o4507219761954816.ingest.us.sentry.io/4507219764183040
  exception-resolver-order: -2147483647 # to capture exceptions in GlobalExceptionHandler
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0