name: Deploy to cloudtype
on:
  push:
    branches:
      - testdevelop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: mingle-dev-space/mingle-api
          stage: main
          yaml: |
            name: mingle-api
            app: java@17
            options:
              ports: "7070"
              healthz: /auth/ping
              env:
                - name: AWS_ACCESS_KEY_ID
                  value: ${{ secrets.AWS_ACCESS_KEY_ID }}
                - name: AWS_SECRET_ACCESS_KEY
                  value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}